import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        {/* Global Nav */}
        <header className="sticky top-0 z-50 border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <nav className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6">
            <Link href="/" className="text-sm font-medium">QuSuite</Link>
            <div className="flex gap-4 text-sm">
              <Link href="/qsuite/architecture" className="text-muted-foreground hover:text-foreground">Architecture</Link>
              <Link href="/qsuite/flow" className="text-muted-foreground hover:text-foreground">Flow</Link>
              <Link href="/qsuite/messaging" className="text-muted-foreground hover:text-foreground">Messaging</Link>
            </div>
          </nav>
        </header>
        {children}
        <VisualEditsMessenger />
      </body>
    </html>
  );
}